import test from 'node:test';
import assert from 'node:assert/strict';
import {getKiConfig,updateOwnerOptIn,requestKiTask,createKiSourceGuard,validateKiChallenge} from './ki-client.js';
const state={effective:true,mode:'direkt',mailReady:true,capabilities:{freeText:true,mailDraft:true,appointmentDraft:true}};
const wire={success:true,active:true,mode:'direkt',operatorReady:true,ownerActive:true,mailReady:true,capabilities:state.capabilities,optIn:{informationVersion:'2026-10-08-v1',decidedAt:'2026-10-08T12:00:00Z'}};
const response=(data,status=200)=>({ok:status>=200&&status<300,status,json:async()=>data});
const challenge=()=>{const expiresAt=Date.now()+60000;return {challengeId:'a'.repeat(64)+'.'+expiresAt,expiresAt,candidates:[{id:'p1',text:'Synthetic Müller',type:'PERSON'}]};};
function taskDeps(overrides={}) {return {getKiConfig:async()=>state,getToken:async()=>'synthetic',fetchImpl:async()=>response({success:true,draft:{subject:'Synthetic'}}),...overrides};}
for(const [name,patch] of Object.entries({serveroff:{active:false},stringactive:{active:'true'},stringoperator:{operatorReady:'true'},stringowner:{ownerActive:'true'},unknownmode:{mode:'<script>'},aus:{mode:'aus'}})) {
 test(`configuration fail-closed: ${name}`,async()=>{assert.equal((await getKiConfig({getToken:async()=>'synthetic',fetchImpl:async()=>response({...wire,...patch})})).effective,false);});
}
test('nested owner metadata and explicit capabilities',async()=>{const cfg=await getKiConfig({getToken:async()=>'synthetic',fetchImpl:async()=>response(wire)});assert.equal(cfg.effective,true);assert.equal(cfg.informationVersion,wire.optIn.informationVersion);assert.equal(cfg.capabilities.freeText,true);});
test('employee reads minimal healthstate',async()=>{let url;const cfg=await getKiConfig({isOwner:()=>false,getToken:async()=>'synthetic',fetchImpl:async u=>{url=u;return response({ok:true,active:true,mode:'direkt',capabilities:state.capabilities});}});assert.match(url,/_healthstate$/);assert.equal(cfg.effective,true);});
test('network and HTTP errors never expose arbitrary text',async()=>{for(const fetchImpl of [async()=>{throw Error('PHI_SENTINEL');},async()=>response({error:'PHI_SENTINEL'},403)]){const cfg=await getKiConfig({getToken:async()=>'synthetic',fetchImpl});assert.equal(cfg.effective,false);assert.ok(!JSON.stringify(cfg).includes('PHI_SENTINEL'));}});
for(const options of [{enabled:'false'},{enabled:true,tenantId:'foreign'},{enabled:true,informationVersion:'old'}]) test(`invalid owner payload rejected before network ${JSON.stringify(options)}`,async()=>{let n=0;await assert.rejects(()=>updateOwnerOptIn(options,{getToken:async()=>'synthetic',fetchImpl:async()=>{n++;}}));assert.equal(n,0);});
test('owner false rejected and valid request sends only exact fields',async()=>{await assert.rejects(()=>updateOwnerOptIn({enabled:true},{isOwner:()=>false}));let sent;await updateOwnerOptIn({enabled:false},{getToken:async()=>'synthetic',fetchImpl:async(u,o)=>{sent=JSON.parse(o.body);return response({success:true});}});assert.deepEqual(sent,{enabled:false,informationVersion:'2026-10-08-v1'});});
test('unknown task and tenant input rejected with no fetch',async()=>{for(const [task,payload] of [['../config',{}],['b2c-draft',{tenantId:'other'}]]){let n=0;await assert.rejects(()=>requestKiTask(task,payload,taskDeps({fetchImpl:async()=>{n++;}})));assert.equal(n,0);}});
test('mail requires explicit freeText capability',async()=>{let n=0;await assert.rejects(()=>requestKiTask('b2c-draft',{},taskDeps({getKiConfig:async()=>({...state,capabilities:{mailDraft:true}}),fetchImpl:async()=>{n++;}})));assert.equal(n,0);});
test('appointment requires mail readiness even with active KI',async()=>{let n=0;await assert.rejects(()=>requestKiTask('appointment-confirm-draft',{},taskDeps({getKiConfig:async()=>({...state,mailReady:false}),fetchImpl:async()=>{n++;}})));assert.equal(n,0);});
test('task success must explicitly equal true',async()=>{await assert.rejects(()=>requestKiTask('series-rank',{},taskDeps({fetchImpl:async()=>response({draft:{}})})));});
test('cancel causes one local API call and no retry',async()=>{let n=0;await assert.rejects(()=>requestKiTask('b2c-draft',{},taskDeps({fetchImpl:async()=>{n++;return response({code:'KI_RUECKFRAGE',challenge:challenge()},409);},zeigeKiRueckfrageDialog:async()=>null})),{code:'KI_RUECKFRAGE_ABGEBROCHEN'});assert.equal(n,1);});
test('retry is single and uses fresh token',async()=>{let n=0,t=0;await assert.rejects(()=>requestKiTask('b2c-draft',{},taskDeps({getToken:async()=>`synthetic-${++t}`,fetchImpl:async(u,o)=>{n++;assert.equal(o.headers.Authorization,`Bearer synthetic-${n}`);return response({code:'KI_RUECKFRAGE',challenge:challenge()},409);},zeigeKiRueckfrageDialog:async()=>({choices:[{id:'p1',action:'maskieren'}]})})),{code:'KI_RETRY_LIMIT'});assert.equal(n,2);assert.equal(t,2);});
for(const [label,choices] of [['subset',[]],['duplicate',[{id:'p1',action:'maskieren'},{id:'p1',action:'maskieren'}]],['unknown',[{id:'other',action:'maskieren'}]]]) test(`choices reject ${label}`,async()=>{let n=0;await assert.rejects(()=>requestKiTask('b2c-draft',{},taskDeps({fetchImpl:async()=>{n++;return response({code:'KI_RUECKFRAGE',challenge:challenge()},409);},zeigeKiRueckfrageDialog:async()=>({choices})})),{code:'KI_CHOICES_INVALID'});assert.equal(n,1);});
test('missing fresh token blocks retry',async()=>{let n=0,t=0;await assert.rejects(()=>requestKiTask('b2c-draft',{},taskDeps({getToken:async()=>++t===1?'synthetic':null,fetchImpl:async()=>{n++;return response({code:'KI_RUECKFRAGE',challenge:challenge()},409);},zeigeKiRueckfrageDialog:async()=>({choices:[{id:'p1',action:'maskieren'}]})})),{code:'KI_AUTH_REQUIRED'});assert.equal(n,1);});
test('edit while getting fresh token blocks retry',async()=>{let n=0,t=0,dirty=false;await assert.rejects(()=>requestKiTask('b2c-draft',{},taskDeps({getToken:async()=>{if(++t===2)dirty=true;return 'synthetic';},isSourceEdited:()=>dirty,fetchImpl:async()=>{n++;return response({code:'KI_RUECKFRAGE',challenge:challenge()},409);},zeigeKiRueckfrageDialog:async()=>({choices:[{id:'p1',action:'maskieren'}]})})),{code:'KI_SOURCE_EDITED'});assert.equal(n,1);});
test('jeton never opens forged freetext challenge',async()=>{let opened=0;await assert.rejects(()=>requestKiTask('series-rank',{},taskDeps({getKiConfig:async()=>({...state,mode:'jeton'}),fetchImpl:async()=>response({code:'KI_RUECKFRAGE',challenge:challenge()},409),zeigeKiRueckfrageDialog:async()=>{opened++;}})));assert.equal(opened,0);});
test('source guard remembers edit then undo and programmatic changes, cleans listeners',()=>{const field=new EventTarget();field.value='first';const guard=createKiSourceGuard([field]);field.value='next';assert.equal(guard.isSourceEdited(),true);field.value='first';field.dispatchEvent(new Event('input'));assert.equal(guard.isSourceEdited(),true);guard.dispose();});
test('challenge strict bounds and expiry',()=>{const c=challenge();assert.equal(validateKiChallenge(c),true);for(const patch of [{expiresAt:Date.now()-1},{expiresAt:Date.now()+600000},{candidates:[...c.candidates,...c.candidates]},{challengeId:null}])assert.equal(validateKiChallenge({...c,...patch}),false);});
