-- =============================================================================
-- VERSCHOBEN am 03.09.2026 — diese Datei ist nur noch ein Verweis
-- =============================================================================
--
-- Die SQL steht jetzt bei ihren Geschwistern:
--
--     supabase/migrations/20260902090000_services_kostentraeger_typ.sql
--
-- Dort steht auch der Rueckbau, die Kontrollabfragen und die Begruendung der
-- Datenmodell-Entscheidung (text + CHECK, NULL erlaubt).
--
-- WARUM VERSCHOBEN
-- Zwei Kopien derselben SQL driften auseinander — davor warnt `OFFEN.md` in
-- diesem Ordner selbst. Also gibt es sie genau einmal. `sql-melih/` ist laut
-- CLAUDE.md ohnehin archivisch ("iş kapandı"); Schemaaenderungen gehoeren nach
-- `supabase/migrations/`.
--
-- AUSFUEHREN
-- Unveraendert von Hand im Supabase-SQL-Editor, Projekt njvuclullotbksskpwgk
-- (Produkt, NICHT das Ops-Projekt farkaejociddtgqkusvm). Mehrfach ausfuehrbar,
-- mit einer Einschraenkung, die im Kopf der Migrationsdatei steht: ein zweiter
-- Lauf ueberschreibt zwar keine gepflegten Werte, wandelt aber bewusst auf
-- "automatisch" (NULL) gestellte Leistungen um.
-- =============================================================================
